- name: This sets up an apache2 webserver
  hosts: aws_ec2
  become: yes
  remote_user: ubuntu
  gather_facts: true
  vars:
    ansible_ssh_private_key_file: "/etc/ansible/euran-jenkins"  
    ansible_ssh_user: "ubuntu"
  tasks:
  - name: "Install apache2 and php packages"
    package:
        name:
          - "apache2"
          - "php"
        state: present
  - name: Update apt cache and make sure Vim, Curl and Unzip are installed
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - vim
        - curl
        - unzip      
  - name: "copy code from GitHub"
    get_url:
        url: https://www.shubhammishra.in
        dest: "/var/www/html/index.php"
  - name: "Start apachw2 services"
    service:
        name: apache2
        state: started
  - name: apt Install Packages
    apt: name={{item}} state=latest
    with_items:
       - wget
  - name: terraform install
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.3.6/terraform_1.3.6_linux_amd64.zip
      dest: /usr/bin
      remote_src: True
